unbind C-b
set -g prefix C-Space
bind C-Space send-prefix
set -s escape-time 0 # Address vim mode switching delay
set -g display-time 2000 # Increase tmux messages display duration from 750ms
set -g status-interval 5 # Refresh 'status-left' and 'status-right' more often, from every 15s to 5s
# setw -g automatic-rename off
set -g status-keys emacs 
set -g mouse on
setw -g mode-keys vi
set -g history-limit 5000
set -s set-clipboard external
set -g allow-passthrough on
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -g focus-events on

# --- Keybindings ---
bind p display-popup -E -S 'fg=purple' -T "Scratch" "zsh"
bind g display-popup -E -S 'fg=purple,bg=black' -T "lg" -d "#{pane_current_path}" -w 80% -h 80% 'lazygit'
bind f copy-mode
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel
# --- Tabs (windows) ---
bind t new-window -c "#{pane_current_path}"
bind b previous-window  

bind -n M-N next-window
bind -n M-B previous-window
bind -n M-a select-layout main-vertical
bind -n M-A select-layout main-horizontal
bind -n M-T new-window -c "#{pane_current_path}"
# --- Splits ---
bind 5 split-window -h
bind -n M-% split-window -h
bind % split-window -h
bind '"' split-window -v
bind -n M-'"' split-window -v
# --- Session management ---
bind s choose-session
bind S new-session
bind R command-prompt -I "#S" "rename-session '%%'"
bind -n M-M switch-client -n
bind -n M-Z resize-pane -Z

bind t new-window -c "#{pane_current_path}"
bind 5 split-window -h -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"
bind -n M-% split-window -h -c "#{pane_current_path}"
bind -n M-'"' split-window -v -c "#{pane_current_path}"
bind r source-file ~/.tmux.conf \; display-message "Reloaded tmux.conf"
bind = select-layout tiled
# --- Style ---
set -g status-style "bg=#272822,fg=#F8F8F2"
#set -g status-left-length 30
set -g status-left "#[fg=#272822,bg=#A6E22E,bold] #S #[fg=#A6E22E,bg=#272822]"
set -g window-status-format "#[fg=#75715E,bg=#272822] #I:#W "
set -g window-status-current-format "#[fg=#272822,bg=#66D9EF,bold] #I:#W #[fg=#66D9EF,bg=#272822]"
#set -g window-status-separator ""
#set -g status-right-length 250
#set -g status-right "#[fg=#F8F8F2,bg=#272822] #H  %Y-%m-%d %H:%M  #(gitmux '#{pane_current_path}') "
set -g pane-border-style "fg=#49483E"
set -g pane-active-border-style "fg=#66D9EF"
set -g message-style "bg=#272822,fg=#F8F8F2"

# --- Pane Nav, vim integration --- Smart pane switching with awareness of Vim splits.  See: https://github.com/christoomey/vim-tmux-navigator
vim_pattern='(\S+/)?g?\.?(view|l?n?vim?x?|fzf)(diff)?(-wrapped)?'
is_vim="ps -o state= -o comm= -t '#{pane_tty}' | grep -iqE '^[^TXZ ]+ +${vim_pattern}$'"
bind -n M-H if-shell "$is_vim" 'send-keys C-h'  'select-pane -L'
bind -n M-J if-shell "$is_vim" 'send-keys C-j'  'select-pane -D'
bind -n M-K if-shell "$is_vim" 'send-keys C-k'  'select-pane -U'
bind -n M-L if-shell "$is_vim" 'send-keys C-l'  'select-pane -R'
tmux_version='$(tmux -V | sed -En "s/^tmux ([0-9]+(.[0-9]+)?).*/\1/p")'
if-shell -b '[ "$(echo "$tmux_version < 3.0" | bc)" = 1 ]' "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\'  'select-pane -l'"
if-shell -b '[ "$(echo "$tmux_version >= 3.0" | bc)" = 1 ]' "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\\\'  'select-pane -l'"
bind-key -T copy-mode-vi 'C-h' select-pane -L
bind-key -T copy-mode-vi 'C-j' select-pane -D
bind-key -T copy-mode-vi 'C-k' select-pane -U
bind-key -T copy-mode-vi 'C-l' select-pane -R
bind-key -T copy-mode-vi 'C-\' select-pane -l
set -g window-status-format "#[fg=#75715E,bg=#272822] #I:#W#{?window_zoomed_flag, Z,} "
set -g window-status-current-format "#[fg=#272822,bg=#66D9EF,bold] #I:#W#{?window_zoomed_flag, Z,} #[fg=#66D9EF,bg=#272822]"

