music_directory        "/Users/kevin/Music/mpd"
playlist_directory     "/Users/kevin/.config/mpd/personal/playlists"

db_file                "/Users/kevin/.config/mpd/personal/database"
state_file             "/Users/kevin/.config/mpd/personal/state"
sticker_file           "/Users/kevin/.config/mpd/personal/sticker.sql"
log_file               "/Users/kevin/.config/mpd/personal/mpd.log"
pid_file               "/Users/kevin/.config/mpd/personal/mpd.pid"

bind_to_address        "127.0.0.1"
port                   "6600"

follow_inside_symlinks "yes"
follow_outside_symlinks "yes"

audio_output {
    type        "osx"
    name        "Mac audio"
    mixer_type  "software"
}

audio_output {
    type        "fifo"
    name        "Cava"
    path        "/tmp/mpd.fifo"
    format      "44100:16:2"
}
